controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

#index:
#    path: /blog
#    controller: App/Controller/BlogController::index